---
    name: Upload vers github pages
    
    on:
      workflow_dispatch:
      push:
        branches:
          - preprod
    
    jobs:
      # Build job
      deploy:
        runs-on: [self-hosted, linux, ARM64]

        steps:
          - uses: actions/checkout@v4
          - name: test env and deploy a sample html file
            run: |
              cp index.html /var/www/html/ 
              cp /assets /var/www/html/
              cp /images /var/www/html/
    
    